import { supabase } from "@/integrations/supabase/client";

export type TitleMessage = { role: "user" | "assistant"; content: string };

/**
 * Heuristic: detect titles that look like a naive first-message slice.
 * The two existing systems generate titles in these shapes:
 *   - General Chat: input.slice(0, 50)        → up to 50 chars, no ellipsis
 *   - Project Chat: input.slice(0, 47) + "..." → ends with "..."
 * Plus the literal placeholder "New Chat".
 */
export function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  if (!title) return true;
  const t = title.trim();
  if (!t) return true;
  if (t === "New Chat") return true;
  if (t.endsWith("...")) return true;        // project-chat slice marker
  if (t.length >= 40) return true;           // general-chat raw 50-char slice
  return false;
}

/**
 * Calls the generate-chat-title edge function and returns a clean title,
 * or null on failure. Caller is responsible for not invoking this twice
 * for the same chat (use a Set/ref guard).
 */
export async function generateChatTitle(
  messages: TitleMessage[],
): Promise<string | null> {
  try {
    // Need at least 1 user + 1 assistant message
    const hasUser = messages.some((m) => m.role === "user" && m.content.trim());
    const hasAssistant = messages.some((m) => m.role === "assistant" && m.content.trim());
    if (!hasUser || !hasAssistant) return null;

    const { data, error } = await supabase.functions.invoke("generate-chat-title", {
      body: { messages: messages.slice(0, 5) },
    });
    if (error) {
      console.warn("[generateChatTitle] edge error:", error);
      return null;
    }
    const title = (data as any)?.title;
    if (typeof title !== "string" || !title.trim()) return null;
    return title.trim();
  } catch (err) {
    console.warn("[generateChatTitle] exception:", err);
    return null;
  }
}
