import { useState, useRef, useEffect, useCallback, forwardRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Trash2, Loader2, Download, Copy, Check,
  Sparkles,
} from "lucide-react";

import ReactMarkdown from "react-markdown";
import duncanAvatar from "@/assets/duncan-avatar.jpeg";
import remarkGfm from "remark-gfm";
import { useNavigate, useLocation } from "react-router-dom";
import WelcomeModal from "@/components/WelcomeModal";
import { useNormanChat } from "@/hooks/useNormanChat";
import type { ChatAttachment } from "@/hooks/useNormanChat";
import ChatInput from "@/components/chat/ChatInput";
import PendingWriteCard from "@/components/chat/PendingWriteCard";
import ToolStatusPills from "@/components/chat/ToolStatusPills";

import { supabase } from "@/integrations/supabase/client";
import { useGeneralChatsContext } from "@/hooks/GeneralChatsContext";
import { useProfile } from "@/hooks/useProfile";
import { generateChatTitle, isAutoGeneratedTitle } from "@/lib/generateChatTitle";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { HomeDashboard } from "@/components/home/HomeDashboard";
import VoiceModeOverlay from "@/components/chat/VoiceModeOverlay";


const getGreeting = () => {
  const hour = new Date().getHours();
  if (hour < 12) return "Good morning";
  if (hour < 17) return "Good afternoon";
  return "Good evening";
};

/* ── Copy button ── */
const CopyButton = ({ content, messageRef }: { content: string; messageRef: React.RefObject<HTMLDivElement> }) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    try {
      const htmlContent = messageRef.current?.innerHTML || content;
      await navigator.clipboard.write([
        new ClipboardItem({
          "text/html": new Blob([htmlContent], { type: "text/html" }),
          "text/plain": new Blob([content], { type: "text/plain" }),
        }),
      ]);
    } catch {
      await navigator.clipboard.writeText(content);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button onClick={handleCopy} className="flex items-center gap-1 rounded-md px-2 py-1 text-[10px] font-medium text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors" title="Copy response">
      {copied ? <Check className="h-3 w-3 text-primary" /> : <Copy className="h-3 w-3" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
};

/* ── Helpers ── */
const getInitials = (name?: string | null) => {
  if (!name) return "Me";
  const parts = name.trim().split(/\s+/).filter(Boolean).slice(0, 2);
  const initials = parts.map((p) => p[0]?.toUpperCase()).join("");
  return initials || "Me";
};

/* ── Message bubble ── */
const MessageBubble = forwardRef<HTMLDivElement, {
  msg: { role: "user" | "assistant"; content: string };
  downloadingUrl: string | null;
  handleAuthenticatedDownload: (url: string) => void;
  userName: string;
  userAvatarUrl?: string | null;
}>(({ msg, downloadingUrl, handleAuthenticatedDownload, userName, userAvatarUrl }, ref) => {
  const contentRef = useRef<HTMLDivElement>(null);
  const isUser = msg.role === "user";
  const senderLabel = isUser ? userName : "Duncan";

  return (
    <motion.div ref={ref} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }} className={`flex gap-2 sm:gap-3 ${isUser ? "justify-end" : "justify-start"}`}>
      {!isUser && (
        <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg overflow-hidden border border-primary/20">
          <img src={duncanAvatar} alt="Duncan" className="h-full w-full object-cover object-[50%_30%] scale-150" />
        </div>
      )}
      <div className={`flex flex-col min-w-0 max-w-[85%] sm:max-w-[80%] ${isUser ? "items-end" : "items-start"}`}>
        <p className={`mb-1 text-[10px] font-medium uppercase tracking-wider text-muted-foreground ${isUser ? "text-right" : "text-left"}`}>
          {senderLabel}
        </p>
        <div className={`text-[15px] overflow-hidden rounded-2xl px-4 sm:px-5 py-3 sm:py-4 ${isUser ? "bg-primary text-primary-foreground" : "bg-card border border-border text-foreground"}`}>
          {!isUser ? (
            <>
              <div ref={contentRef} className="max-w-none text-[15px] sm:text-[16px] leading-[1.75] tracking-[-0.003em] overflow-x-auto break-words [&_h1]:text-xl [&_h1]:sm:text-2xl [&_h1]:font-semibold [&_h1]:tracking-tight [&_h1]:mt-6 [&_h1]:sm:mt-8 [&_h1]:mb-3 [&_h1]:text-foreground [&_h2]:text-lg [&_h2]:sm:text-xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:mt-6 [&_h2]:sm:mt-7 [&_h2]:mb-3 [&_h2]:text-foreground [&_h3]:text-base [&_h3]:sm:text-lg [&_h3]:font-semibold [&_h3]:mt-5 [&_h3]:mb-2 [&_h3]:text-foreground [&_p]:text-foreground/90 [&_p]:mb-4 [&_p]:leading-[1.75] [&_p:last-child]:mb-0 [&_strong]:text-foreground [&_strong]:font-semibold [&_em]:italic [&_code]:text-primary [&_code]:bg-secondary [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded-md [&_code]:text-[0.9em] [&_code]:font-mono [&_pre]:bg-secondary [&_pre]:border [&_pre]:border-border [&_pre]:rounded-xl [&_pre]:my-4 [&_pre]:p-4 [&_pre]:overflow-x-auto [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-[13px] [&_li]:text-foreground/90 [&_li]:mb-2 [&_li]:leading-[1.75] [&_li]:pl-1 [&_li>p]:mb-1 [&_ul]:my-4 [&_ul]:pl-6 [&_ul]:list-disc [&_ul]:marker:text-muted-foreground [&_ol]:my-4 [&_ol]:pl-6 [&_ol]:list-decimal [&_ol]:marker:text-muted-foreground [&_hr]:my-6 [&_hr]:border-border/60 [&_blockquote]:border-l-2 [&_blockquote]:border-primary/40 [&_blockquote]:pl-4 [&_blockquote]:my-4 [&_blockquote]:italic [&_blockquote]:text-foreground/80 [&_table]:my-5 [&_table]:w-full [&_table]:border-collapse [&_table]:text-sm [&_table]:block [&_table]:sm:table [&_table]:overflow-x-auto [&_thead]:border-b [&_thead]:border-border [&_th]:px-3 [&_th]:py-2 [&_th]:text-sm [&_th]:font-semibold [&_th]:text-foreground [&_th]:text-left [&_td]:px-3 [&_td]:py-2 [&_td]:text-sm [&_td]:text-foreground/90 [&_tr]:border-b [&_tr]:border-border/40 [&_a]:underline-offset-[3px]">
                <ReactMarkdown remarkPlugins={[remarkGfm]} components={{
                  a: ({ href, children }) => {
                    const isDownloadLink = href?.includes("azure-blob-api") && (href?.includes("blob_path") || href?.includes("path="));
                    if (isDownloadLink && href) {
                      const isDownloading = downloadingUrl === href;
                      return (
                        <button onClick={() => handleAuthenticatedDownload(href)} disabled={isDownloading} className="inline-flex items-center gap-1.5 text-primary hover:text-primary/80 underline underline-offset-2 font-medium disabled:opacity-50">
                          {isDownloading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
                          {children}
                        </button>
                      );
                    }
                    return <a href={href} target="_blank" rel="noopener noreferrer" className="text-primary hover:text-primary/80 underline underline-offset-2">{children}</a>;
                  },
                }}>{msg.content}</ReactMarkdown>
              </div>
              <div className="mt-3 flex justify-start">
                <CopyButton content={msg.content} messageRef={contentRef} />
              </div>
            </>
          ) : (
            <span className="whitespace-pre-wrap break-words">{msg.content}</span>
          )}
        </div>
      </div>
      {isUser && (
        <Avatar className="mt-1 h-7 w-7 shrink-0 border border-primary/20">
          {userAvatarUrl ? <AvatarImage src={userAvatarUrl} alt={userName} /> : null}
          <AvatarFallback className="text-[10px] font-semibold bg-primary/10 text-primary">
            {getInitials(userName)}
          </AvatarFallback>
        </Avatar>
      )}
    </motion.div>
  );
});

MessageBubble.displayName = "MessageBubble";

/* ── Main Page ── */
const Index = () => {
  const { messages, isLoading, extractionProgress, pendingWrites, toolStatuses, lastError, send, sendBriefing, clearMessages, setMessages, confirmWrite, cancelWrite, retryLastTurn } = useNormanChat();
  const navigate = useNavigate();
  const briefingTriggered = useRef(false);
  const [briefingError, setBriefingError] = useState(false);
  const [briefingTimestamp, setBriefingTimestamp] = useState<string | null>(null);
  const chatOps = useGeneralChatsContext();
  const { profile } = useProfile();
  const userDisplayName = profile?.display_name || "You";
  const userAvatarUrl = profile?.avatar_url || null;

  const [downloadingUrl, setDownloadingUrl] = useState<string | null>(null);
  const [weather, setWeather] = useState<{ temp: number; description: string } | null>(null);
  
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  
  const [voiceOpen, setVoiceOpen] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const savingRef = useRef(false);
  const skipInitialHydrationChatIdRef = useRef<string | null>(null);

  // Load messages when active chat changes
  useEffect(() => {
    if (!chatOps.activeChatId) {
      clearMessages();
      return;
    }

    if (skipInitialHydrationChatIdRef.current === chatOps.activeChatId) {
      skipInitialHydrationChatIdRef.current = null;
      return;
    }

    (async () => {
      const loaded = await chatOps.loadMessages(chatOps.activeChatId!);
      setMessages(loaded.map((m) => ({ role: m.role, content: m.content })));
    })();
  }, [chatOps.activeChatId]);

  // ── Daily Briefing flow (server is single source of truth) ──
  // 1. POST /daily-briefing → returns either { already_shown_today } or full data
  // 2. If new data → stream via sendBriefing()
  // 3. On stream success → POST /mark-briefing-shown to lock for the day
  // No sessionStorage gate. No pre-emptive locking. Retry-safe.
  const runBriefing = useCallback(async () => {
    setBriefingError(false);
    briefingTriggered.current = true;

    try {
      console.info("[Duncan] briefing: fetch start");
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        console.warn("[Duncan] briefing: no session, aborting");
        briefingTriggered.current = false;
        return;
      }

      const resp = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/daily-briefing`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${session.access_token}`,
          },
        }
      );

      console.info("[Duncan] briefing: API response", resp.status);
      if (!resp.ok) {
        const errText = await resp.text();
        console.error("[Duncan] briefing: API error", resp.status, errText);
        throw new Error(`Briefing fetch failed (${resp.status})`);
      }

      const briefingData = await resp.json();
      if (briefingData?.already_shown_today) {
        console.info("[Duncan] briefing: already shown today, skipping");
        if (briefingData.last_briefing_at) {
          setBriefingTimestamp(briefingData.last_briefing_at);
        }
        return;
      }

      console.info("[Duncan] briefing: streaming via sendBriefing");
      const ok = await sendBriefing(briefingData);

      if (!ok) {
        throw new Error("Briefing stream did not complete");
      }

      // Stream succeeded → NOW lock the day
      try {
        const markResp = await fetch(
          `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/mark-briefing-shown`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${session.access_token}`,
            },
          }
        );
        if (!markResp.ok) {
          console.warn("[Duncan] briefing: mark-shown failed", markResp.status);
        } else {
          const markData = await markResp.json();
          if (markData.last_briefing_at) {
            setBriefingTimestamp(markData.last_briefing_at);
          }
          console.info("[Duncan] briefing: marked as shown");
        }
      } catch (markErr) {
        console.warn("[Duncan] briefing: mark-shown threw", markErr);
      }
    } catch (err) {
      console.error("[Duncan] briefing: failure reason →", err);
      setBriefingError(true);
      briefingTriggered.current = false; // allow retry
    }
  }, [sendBriefing]);

  useEffect(() => {
    if (briefingTriggered.current) return;

    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (_event, session) => {
        if (!session || briefingTriggered.current) return;
        await runBriefing();
      }
    );

    (async () => {
      if (briefingTriggered.current) return;
      const { data: { session } } = await supabase.auth.getSession();
      if (!session || briefingTriggered.current) return;
      await runBriefing();
    })();

    return () => subscription.unsubscribe();
  }, [runBriefing]);

  useEffect(() => {
    if (!navigator.geolocation) return;
    if (localStorage.getItem("location_consent") !== "true") {
      const consent = window.confirm("Duncan uses your approximate location for weather. Allow?");
      if (!consent) {
        localStorage.setItem("location_consent", "false");
        return;
      }
      localStorage.setItem("location_consent", "true");
    }
    navigator.geolocation.getCurrentPosition(
      async (pos) => {
        try {
          // Round to 2dp (~1km) to avoid sending precise location to 3rd party
          const lat = Math.round(pos.coords.latitude * 100) / 100;
          const lon = Math.round(pos.coords.longitude * 100) / 100;
          const res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code`);
          const data = await res.json();
          const code = data.current.weather_code;
          const desc = code === 0 ? "Clear" : code <= 3 ? "Cloudy" : code <= 48 ? "Foggy" : code <= 67 ? "Rainy" : code <= 77 ? "Snowy" : code <= 82 ? "Showers" : code <= 99 ? "Stormy" : "Clear";
          setWeather({ temp: Math.round(data.current.temperature_2m), description: desc });
        } catch { /* silent */ }
      },
      () => {}
    );
  }, []);

  const handleAuthenticatedDownload = useCallback(async (url: string) => {
    try {
      setDownloadingUrl(url);
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) throw new Error("Not authenticated");
      const response = await fetch(url, { headers: { Authorization: `Bearer ${session.access_token}`, apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY } });
      if (!response.ok) throw new Error("Download failed");
      const blob = await response.blob();
      const contentDisposition = response.headers.get("Content-Disposition");
      const filenameMatch = contentDisposition?.match(/filename="?([^"]+)"?/);
      const filename = filenameMatch?.[1] || "download";
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      URL.revokeObjectURL(a.href);
      a.remove();
    } catch (err) { console.error("Download error:", err); }
    finally { setDownloadingUrl(null); }
  }, []);

  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); }, [messages]);

  const handleChatSubmit = useCallback(async (input: string, attachments: ChatAttachment[]) => {
    if (savingRef.current) return;
    savingRef.current = true;
    setNewChatMode(false);

    let chatId = chatOps.activeChatId;

    // Create chat lazily on first message
    if (!chatId) {
      const title = input.slice(0, 50) || "New Chat";
      chatId = await chatOps.createChat(title);
      if (chatId) {
        skipInitialHydrationChatIdRef.current = chatId;
        chatOps.setActiveChatId(chatId);
      }
    }

    // Save user message
    if (chatId) {
      await chatOps.saveMessage(chatId, "user", input);
    }

    // Send to AI
    send(input, "general", attachments);
    savingRef.current = false;
  }, [chatOps.activeChatId, chatOps, send]);

  // Save assistant responses when they finish streaming
  const prevAssistantContentRef = useRef<string | null>(null);
  // Track which chat IDs we've already auto-titled this session
  const titledChatsRef = useRef<Set<string>>(new Set());
  useEffect(() => {
    if (isLoading || !chatOps.activeChatId) {
      return;
    }

    const lastMsg = messages[messages.length - 1];
    if (
      lastMsg?.role === "assistant" &&
      lastMsg.content.trim() &&
      lastMsg.content !== prevAssistantContentRef.current
    ) {
      prevAssistantContentRef.current = lastMsg.content;
      const activeId = chatOps.activeChatId;
      chatOps.saveMessage(activeId, "assistant", lastMsg.content);

      // Intelligent title generation — once per chat, async, non-blocking
      if (!titledChatsRef.current.has(activeId)) {
        const chat = chatOps.chats.find((c) => c.id === activeId);
        if (chat && isAutoGeneratedTitle(chat.title)) {
          titledChatsRef.current.add(activeId); // optimistic guard
          (async () => {
            const title = await generateChatTitle(
              messages.map((m) => ({ role: m.role, content: m.content })),
            );
            if (title) {
              await chatOps.updateTitle(activeId, title);
            } else {
              // allow retry on next assistant message if generation failed
              titledChatsRef.current.delete(activeId);
            }
          })();
        }
      }
    }
  }, [isLoading, messages, chatOps]);

  const handleQuickAction = (prompt: string) => {
    handleChatSubmit(prompt, []);
  };

  const location = useLocation();
  const [newChatMode, setNewChatMode] = useState(
    () => !!(location.state as any)?.newChat
  );

  useEffect(() => {
    const handler = (event: Event) => {
      const explicit = (event as CustomEvent).detail?.explicit === true;
      if (!explicit) return;

      clearMessages();
      chatOps.startNewChat();
      setNewChatMode(false);
    };
    window.addEventListener("duncan:show-dashboard", handler);
    return () => window.removeEventListener("duncan:show-dashboard", handler);
  }, [clearMessages, chatOps]);

  useEffect(() => {
    if ((location.state as any)?.newChat) {
      clearMessages();
      chatOps.startNewChat();
      setNewChatMode(true);
      navigate(location.pathname, {
        replace: true,
        state: {},
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.key]);

  const handleClearChat = useCallback(() => {
    clearMessages();
    chatOps.startNewChat();
    setNewChatMode(true);
  }, [clearMessages, chatOps]);

  const hasMessages = messages.length > 0;

  return (
    <div className="flex h-full bg-background">
      <WelcomeModal />
      <main className="flex-1 flex flex-col h-full w-full">
        <div className="pointer-events-none fixed top-0 lg:left-64 left-0 right-0 h-72 gradient-radial z-0" />

        {/* Header */}
        <div className="relative z-10 flex items-center gap-3 border-b border-border px-4 sm:px-8 py-3 sm:py-4">
          <div className="flex-1 min-w-0">

            <p className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">
              {new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
            </p>
            <h2 className="text-sm sm:text-lg font-bold text-foreground tracking-tight truncate">
              {getGreeting()}{userDisplayName && userDisplayName !== "You" ? `, ${userDisplayName.split(" ")[0]}` : ""}. Duncan is <span className="text-primary glow-text">operational</span>.
              {weather && <span className="hidden sm:inline ml-2 text-sm font-normal text-muted-foreground">{weather.temp}°C · {weather.description}</span>}
            </h2>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button onClick={() => navigate("/whats-new")} className="flex items-center gap-1.5 rounded-lg border border-primary/20 bg-primary/10 px-2 sm:px-3 py-1.5 sm:py-2 text-xs font-medium text-primary hover:bg-primary/20 transition-colors">
              <Sparkles className="h-3 w-3" /> <span className="hidden sm:inline">What's New</span>
            </button>
            {hasMessages && (
              <button onClick={handleClearChat} className="flex items-center gap-1.5 rounded-lg border border-border bg-card px-2 sm:px-3 py-1.5 sm:py-2 text-xs text-muted-foreground hover:text-foreground transition-colors">
                <Trash2 className="h-3 w-3" /> <span className="hidden sm:inline">New Chat</span>
              </button>
            )}
          </div>
        </div>







        {/* Briefing status banners */}
        {briefingError && (
          <div className="relative z-10 mx-4 sm:mx-8 mt-3 flex items-center justify-between gap-3 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-2.5 text-xs">
            <span className="text-destructive-foreground">
              Your daily briefing couldn't load.
            </span>
            <button
              onClick={() => runBriefing()}
              className="inline-flex items-center gap-1.5 rounded-md border border-destructive/40 bg-background px-2.5 py-1 text-xs font-medium text-foreground hover:bg-secondary transition-colors"
            >
              Retry
            </button>
          </div>
        )}
        {isLoading && !hasMessages && !briefingError && (
          <div className="relative z-10 mx-4 sm:mx-8 mt-3 flex items-center gap-2 rounded-lg border border-border bg-card/60 px-4 py-2.5 text-xs text-muted-foreground">
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
            Generating your briefing…
          </div>
        )}
        {briefingTimestamp && !briefingError && (
          <div className="relative z-10 mx-4 sm:mx-8 mt-2 text-[10px] text-muted-foreground/70">
            Last briefing at {new Date(briefingTimestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </div>
        )}

        {/* Content area */}
        <div ref={scrollRef} className="relative z-10 flex-1 overflow-y-auto px-4 sm:px-8 py-4 sm:py-6">
          {!hasMessages ? (
            newChatMode ? (
              <div className="mx-auto w-full max-w-3xl flex flex-col items-center justify-center min-h-full text-center px-4 py-12">
                <div className="h-14 w-14 rounded-2xl overflow-hidden border border-primary/20 mb-5">
                  <img src={duncanAvatar} alt="Duncan" className="h-full w-full object-cover object-[50%_30%] scale-150" />
                </div>
                <h1 className="text-2xl sm:text-3xl font-semibold text-foreground tracking-tight">
                  {getGreeting()}, {userDisplayName.split(" ")[0] || "there"}
                </h1>
                <p className="mt-2 text-sm text-muted-foreground max-w-md">
                  Ask me anything, or start with what's on your mind.
                </p>
              </div>
            ) : (
              <HomeDashboard userName={userDisplayName.split(" ")[0] || "you"} />
            )
          ) : (
            <div className="mx-auto max-w-3xl space-y-6 sm:space-y-8">
              <AnimatePresence initial={false}>
                {messages.map((msg, i) => (
                  <MessageBubble key={i} msg={msg} downloadingUrl={downloadingUrl} handleAuthenticatedDownload={handleAuthenticatedDownload} userName={userDisplayName} userAvatarUrl={userAvatarUrl} />
                ))}
              </AnimatePresence>
              {isLoading && messages[messages.length - 1]?.role !== "assistant" && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-center gap-3">
                   <div className="flex h-7 w-7 items-center justify-center rounded-lg overflow-hidden border border-primary/20">
                     <img src={duncanAvatar} alt="Duncan" className="h-full w-full object-cover object-[50%_30%] scale-150" />
                  </div>
                  <div className="flex flex-col gap-1.5 text-muted-foreground text-sm">
                    <div className="flex items-center gap-2">
                      <Loader2 className="h-3.5 w-3.5 animate-spin" /> Duncan is thinking…
                    </div>
                    <ToolStatusPills statuses={toolStatuses} />
                  </div>
                </motion.div>
              )}
              {!isLoading && toolStatuses.length > 0 && (
                <ToolStatusPills statuses={toolStatuses} />
              )}
              {pendingWrites.length > 0 && (
                <div className="space-y-2">
                  {pendingWrites.map((p) => (
                    <PendingWriteCard key={p.pendingId} pending={p} onConfirm={confirmWrite} onCancel={cancelWrite} />
                  ))}
                </div>
              )}
              {lastError && !isLoading && (
                <div className="flex items-center justify-between gap-3 rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs">
                  <span className="text-destructive">{lastError}</span>
                  <button onClick={retryLastTurn} className="rounded-md border border-border bg-background px-2.5 py-1 text-xs font-medium hover:bg-secondary transition-colors">
                    Retry
                  </button>
                </div>
              )}
            </div>
          )}
        </div>


        {/* Prompt input */}
        <ChatInput
          onSubmit={handleChatSubmit}
          isLoading={isLoading}
          extractionProgress={extractionProgress}
          onVoiceToggle={() => setVoiceOpen((v) => !v)}
          isVoiceActive={voiceOpen}
        />
      </main>
      
      <VoiceModeOverlay
        open={voiceOpen}
        onClose={() => setVoiceOpen(false)}
        chat={{
          messages,
          isLoading,
          send: (text: string) => handleChatSubmit(text, []),
        }}
      />
    </div>
  );
};

export default Index;
