import { useState, useRef, useEffect, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  ArrowLeft, Plus, MessageSquare, MessagesSquare, Send, Loader2, Settings2, Users,
  Upload, FileText, Sparkles, Trash2, RefreshCw, PanelRightOpen, X, Menu,  Pencil, Check,
} from "lucide-react";
import { ProjectTeamChatPanel } from "@/components/projects/ProjectTeamChatPanel";
import { useProjectTeamChatUnread } from "@/hooks/useProjectTeamChatUnread";
import { useIsAdmin } from "@/hooks/useUserRoles";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { supabase } from "@/integrations/supabase/client";
import { useProjects, useProjectChats, useProjectChat, useProjectFiles, useProjectMembers } from "@/hooks/useProjects";
import { useUserProfiles } from "@/hooks/useWorkstreams";
import { useProfile } from "@/hooks/useProfile";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import duncanAvatar from "@/assets/duncan-avatar.jpeg";
import { generateChatTitle, isAutoGeneratedTitle } from "@/lib/generateChatTitle";
import ChatInput from "@/components/chat/ChatInput";
import type { ChatAttachment } from "@/hooks/useNormanChat";
import { toast } from "sonner";
import { TutorialButton } from "@/components/onboarding/TutorialButton";
import { ProjectOverviewTab } from "@/components/projects/workspace/ProjectOverviewTab";
import { ProjectWorkstreamsTab } from "@/components/projects/workspace/ProjectWorkstreamsTab";
import { ProjectTeamTab } from "@/components/projects/workspace/ProjectTeamTab";
import { ProjectActivityTab } from "@/components/projects/workspace/ProjectActivityTab";
import { PROJECT_STATUS_META } from "@/hooks/useProjectWork";
import { ProjectProgressRing, useProjectProgress } from "@/components/projects/workspace/ProjectProgressRing";
import { formatDay } from "@/components/projects/workspace/shared";

const PROJECT_TABS = [
  { id: "overview", label: "Overview" },
  { id: "chat", label: "Team Chat" },
  { id: "workstreams", label: "Areas of Work" },
  { id: "activity", label: "Activity" },
] as const;

const CHECKLIST_RE = /^\s*[-*]\s*\[\s*[ xX]?\s*\]\s+/;
const HEADING_RE = /^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$/;

function hasChecklist(text: string): boolean {
  if (!text) return false;
  return text.split("\n").some((l) => CHECKLIST_RE.test(l));
}

async function captureChecklistToPlan(text: string, projectId: string) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    toast.error("Not signed in");
    return;
  }
  const lines = text.split("\n");
  let currentGroup: string | null = null;
  const items: Array<{ title: string; group: string | null }> = [];
  for (const raw of lines) {
    const heading = raw.match(HEADING_RE);
    if (heading) {
      currentGroup = heading[2].trim();
      continue;
    }
    if (CHECKLIST_RE.test(raw)) {
      const title = raw.replace(CHECKLIST_RE, "").trim();
      if (title) items.push({ title, group: currentGroup });
    }
  }
  if (items.length === 0) {
    toast("No checklist items detected");
    return;
  }
  // One task system: checklist items become real project tasks.
  const rows = items.map((it) => ({
    title: it.title,
    description: it.group ? it.group : "",
    project_id: projectId,
    card_id: null,
    assignee_id: null,
    due_date: null,
    status: "not_started",
    completed: false,
  }));
  const { error } = await supabase.from("workstream_tasks").insert(rows as any);
  if (error) {
    toast.error(`Couldn't add: ${error.message}`);
    return;
  }
  toast.success(`Added ${items.length} task${items.length === 1 ? "" : "s"} to the project`);
}

export default function ProjectWorkspace() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { projects, loading: projectsLoading, updateProject } = useProjects();
  const project = projects.find(p => p.id === projectId) || null;
  const { chats, loading: chatsLoading, createChat, updateChatTitle, deleteChat } = useProjectChats(projectId || null);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const { messages, loading: msgsLoading, sending, sendMessage } = useProjectChat(activeChatId);
  const { files, uploadFile, extractText, deleteFile, isUploading, isExtracting } = useProjectFiles(projectId || null);
  const { members, loading: membersLoading, addMember, removeMember } = useProjectMembers(projectId || null);
  const { data: userProfiles = [] } = useUserProfiles({ approvedOnly: false });
  const { profile: currentProfile } = useProfile();
  const { user } = useAuth();
  const myDisplayName = currentProfile?.display_name || "You";
  const myAvatarUrl = currentProfile?.avatar_url || null;

  const [mobileOpen, setMobileOpen] = useState(false);
  const [chatListOpen, setChatListOpen] = useState(false);
  const [tab, setTab] = useState<typeof PROJECT_TABS[number]["id"]>("overview");
  const [input, setInput] = useState("");
  const [showSettings, setShowSettings] = useState(false);
  const [showFiles, setShowFiles] = useState(false);
  const [showTeam, setShowTeam] = useState(false);
  const [showCollaborate, setShowCollaborate] = useState(false);
  const { isAdmin } = useIsAdmin();
  const teamChatUnread = useProjectTeamChatUnread(projectId || null);
  const { pct: projectProgress } = useProjectProgress(projectId || null);
  const [editName, setEditName] = useState("");
  const [editPrompt, setEditPrompt] = useState("");
  const [editTemplate, setEditTemplate] = useState("");
  const [selectedMemberId, setSelectedMemberId] = useState("");
  const [manualDeselect, setManualDeselect] = useState(false);
  const [editingChatId, setEditingChatId] = useState<string | null>(null);
  const [editingChatTitle, setEditingChatTitle] = useState("");
  const editChatInputRef = useRef<HTMLInputElement>(null);
  const messagesScrollerRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const cleanedUpRef = useRef(false);
  const titledChatsRef = useRef<Set<string>>(new Set());

  // Clean up empty chats on load (chats titled "New Chat" with no messages)
  useEffect(() => {
    if (chatsLoading || cleanedUpRef.current || chats.length === 0) return;
    cleanedUpRef.current = true;
    const cleanupEmpty = async () => {
      for (const chat of chats) {
        if (chat.title === "New Chat") {
          const { data } = await supabase
            .from("chat_messages")
            .select("id")
            .eq("chat_id", chat.id)
            .limit(1);
          if (!data || data.length === 0) {
            await deleteChat(chat.id);
          }
        }
      }
    };
    cleanupEmpty();
  }, [chatsLoading, chats, deleteChat]);

  // Reset cleanup flag when project changes
  useEffect(() => {
    cleanedUpRef.current = false;
    setManualDeselect(false);
    setActiveChatId(null);
  }, [projectId]);

  // Auto-select first chat (unless user manually deselected)
  useEffect(() => {
    if (chats.length > 0 && !activeChatId && !manualDeselect) {
      setActiveChatId(chats[0].id);
    }
  }, [chats, activeChatId, manualDeselect]);


  // Scroll only the messages panel. Avoid scrollIntoView here: on mobile Safari
  // it can move the whole fixed-height workspace and leave the user trapped at
  // the bottom of the project page.
  useEffect(() => {
    const scroller = messagesScrollerRef.current;
    if (!scroller) return;
    scroller.scrollTo({ top: scroller.scrollHeight, behavior: "smooth" });
  }, [messages]);

  // Auto-resize textarea
  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 160) + "px";
  }, [input]);

  const handleSend = useCallback(async (
    msgInput: string,
    attachments: ChatAttachment[] = [],
  ) => {
    const msg = (msgInput || "").trim();
    if ((!msg && attachments.length === 0) || sending) return;
    setInput("");

    let chatId = activeChatId;

    // If no active chat, create one on first message
    if (!chatId) {
      const title = msg
        ? (msg.length > 50 ? msg.slice(0, 47) + "..." : msg)
        : "New Chat";
      const chat = await createChat(title);
      if (!chat) return;
      chatId = chat.id;
      setActiveChatId(chat.id);
      setManualDeselect(false);
    }

    // Pass chatId directly to handle the case where activeChatId just changed
    const reply = await sendMessage(msg || "Analyze the attached file(s)", chatId, attachments);

    // Intelligent title generation — once per chat, async, non-blocking
    if (reply && chatId && !titledChatsRef.current.has(chatId)) {
      const currentChat = chats.find((c) => c.id === chatId);
      if (currentChat && isAutoGeneratedTitle(currentChat.title)) {
        const targetChatId = chatId;
        titledChatsRef.current.add(targetChatId);
        (async () => {
          const titleMessages = [
            { role: "user" as const, content: msg || "Attached file(s)" },
            { role: "assistant" as const, content: reply },
          ];
          const newTitle = await generateChatTitle(titleMessages);
          if (newTitle) {
            await updateChatTitle(targetChatId, newTitle);
          } else {
            titledChatsRef.current.delete(targetChatId);
          }
        })();
      }
    }
  }, [sending, sendMessage, activeChatId, createChat, chats, updateChatTitle]);

  const handleNewChat = () => {
    // Just deselect current chat - a new chat will be created on first message
    setActiveChatId(null);
    setManualDeselect(true);
  };

  const startRenameChat = (chat: { id: string; title: string }) => {
    setEditingChatId(chat.id);
    setEditingChatTitle(chat.title);
    setTimeout(() => editChatInputRef.current?.focus(), 0);
  };
  const cancelRenameChat = () => {
    setEditingChatId(null);
    setEditingChatTitle("");
  };
  const commitRenameChat = async () => {
    if (!editingChatId) return;
    const next = editingChatTitle.trim().slice(0, 80);
    if (next) {
      await updateChatTitle(editingChatId, next);
      titledChatsRef.current.add(editingChatId);
    }
    cancelRenameChat();
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const fileList = e.target.files;
    if (!fileList) return;
    for (const file of Array.from(fileList)) {
      await uploadFile(file);
    }
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const openSettings = () => {
    setEditName(project?.name || "");
    setEditPrompt(project?.system_prompt || "");
    setEditTemplate((project as any)?.note_template || "");
    setShowSettings(true);
  };

  const saveSettings = async () => {
    if (!projectId) return;
    await updateProject(projectId, {
      name: editName.trim(),
      system_prompt: editPrompt.trim() || null,
      note_template: editTemplate.trim() || null,
    });
    setShowSettings(false);
  };

  const memberIds = new Set(members.map((member) => member.user_id));
  const availableProfiles = userProfiles.filter((profile) => profile.user_id !== project?.user_id && !memberIds.has(profile.user_id));

  const handleAddMember = async () => {
    if (!selectedMemberId) return;
    const ok = await addMember(selectedMemberId);
    if (ok) setSelectedMemberId("");
  };

  const initialsFor = (name: string | null) =>
    (name || "?")
      .split(" ")
      .filter(Boolean)
      .slice(0, 2)
      .map((part) => part[0]?.toUpperCase())
      .join("") || "?";

  const senderNameFor = (msg: typeof messages[number]) => {
    if (msg.role === "assistant") return "Duncan";
    return msg.sender_name || myDisplayName;
  };

  if (!projectId) return null;

  // Show loading while projects are being fetched
  if (projectsLoading) {
    return (
      <div className="flex h-screen overflow-hidden bg-background">
        <main className="flex-1 flex items-center justify-center">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </main>
      </div>
    );
  }

  // Show not-found if project doesn't exist after loading
  if (!project) {
    return (
      <div className="flex h-screen overflow-hidden bg-background">
        <main className="flex-1 flex flex-col items-center justify-center gap-3">
          <p className="text-sm text-muted-foreground">Project not found</p>
          <Button variant="outline" size="sm" onClick={() => navigate("/projects")}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Projects
          </Button>
        </main>
      </div>
    );
  }

  // Count extracted files for status indicator
  const extractedCount = files.filter(f => f.extracted_text).length;

  return (
    <div className="flex h-[100dvh] overflow-hidden bg-background">
      <main className="flex-1 flex flex-col min-h-0 overflow-hidden">
        {/* Header */}
        <header className="flex items-center gap-1.5 sm:gap-3 border-b border-border px-2 sm:px-4 py-3 shrink-0">
          
          <button data-tour="pw-back" onClick={() => navigate("/projects")} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors">
            <ArrowLeft className="h-4 w-4" />
          </button>
          <button
            onClick={() => setChatListOpen(true)}
            className="md:hidden flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors"
            aria-label="Open chat list"
          >
            <Menu className="h-4 w-4" />
          </button>
          <div className="shrink-0 hidden sm:block" title="Project progress">
            <ProjectProgressRing pct={projectProgress} done={0} total={0} size={34} stroke={3.5} />
          </div>
          <div data-tour="pw-title" className="flex-1 min-w-0">
            <h1 className="text-sm font-semibold text-foreground truncate">{project.name}</h1>
            <p className="text-[11px] text-muted-foreground truncate hidden sm:block">
              {[
                (PROJECT_STATUS_META[project.status] || PROJECT_STATUS_META.on_track).label,
                members.find((m) => m.isOwner)?.display_name,
                project.target_date ? `Due ${formatDay(project.target_date)}` : null,
              ].filter(Boolean).join(" · ")}
            </p>
          </div>
          <div className="hidden lg:block">
            <TutorialButton tourId="project_workspace" />
          </div>
          <Button data-tour="pw-files" variant="ghost" size="sm" onClick={() => setShowFiles(true)} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Files">
            <FileText className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Files{files.length > 0 && ` (${files.length})`}</span>
          </Button>
          <Button data-tour="pw-team" variant="ghost" size="sm" onClick={() => setShowTeam(true)} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Team">
            <Users className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Team{members.length > 0 && ` (${members.length})`}</span>
          </Button>
          <Button data-tour="pw-settings" variant="ghost" size="sm" onClick={openSettings} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Settings">
            <Settings2 className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Settings</span>
          </Button>
        </header>

        {/* Tabs */}
        <nav className="flex items-center gap-1 border-b border-border px-2 sm:px-4 shrink-0 overflow-x-auto">
          {PROJECT_TABS.map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`shrink-0 px-3 py-2.5 text-sm transition-colors border-b-2 -mb-px ${
                tab === t.id
                  ? "border-primary text-foreground font-medium"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              }`}
            >
              {t.label}
            </button>
          ))}
        </nav>

        {/* Workspace */}
        <div className="flex-1 flex min-h-0 overflow-hidden">
          {tab !== "chat" && (
            <div className="flex-1 min-h-0 overflow-y-auto">
              {tab === "overview" && (
                <ProjectOverviewTab
                  projectId={projectId}
                  projectName={project.name}
                  description={project.description}
                  members={members}
                  status={project.status}
                  targetDate={project.target_date}
                  onOpenTab={(next) => setTab(next as any)}
                />
              )}
              {tab === "workstreams" && <ProjectWorkstreamsTab projectId={projectId} members={members} />}
              {tab === "activity" && <ProjectActivityTab projectId={projectId} />}
            </div>
          )}
          {tab === "chat" && projectId && (
            <ProjectTeamChatPanel
              projectId={projectId}
              projectName={project?.name || "Project"}
              isOwnerOrAdmin={isAdmin || project?.user_id === user?.id}
              members={members.map((m) => ({ user_id: m.user_id, display_name: m.display_name, avatar_url: m.avatar_url }))}
            />
          )}

          {/* Files Slide-over */}
          {showFiles && (
            <div className="fixed inset-0 z-40 flex justify-end">
              <div className="absolute inset-0 bg-black/30" onClick={() => setShowFiles(false)} />
              <div className="relative w-72 max-w-full bg-background border-l border-border flex flex-col shadow-xl animate-in slide-in-from-right duration-200">
                <div className="p-3 border-b border-border flex items-center justify-between">
                  <h3 className="text-xs font-semibold text-foreground">Project Files</h3>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isUploading}
                      className="h-7 px-2 gap-1 text-[10px]"
                    >
                      {isUploading ? (
                        <Loader2 className="h-3 w-3 animate-spin" />
                      ) : (
                        <Upload className="h-3 w-3" />
                      )}
                      {isUploading ? "Uploading..." : "Upload"}
                    </Button>
                    <button onClick={() => setShowFiles(false)} className="flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors">
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                </div>
                {extractedCount > 0 && (
                  <div className="flex items-center gap-1.5 text-[10px] text-primary px-3 py-1.5 border-b border-border">
                    <Sparkles className="h-3 w-3" />
                    <span>Auto-retrieval active</span>
                  </div>
                )}
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  className="hidden"
                  accept=".pdf,.docx,.txt,.md,.csv,.json,.xml,.yaml,.yml,.jpg,.jpeg,.png,.webp,.gif"
                  onChange={handleFileUpload}
                  disabled={isUploading}
                />
                <ScrollArea className="flex-1">
                  <div className="p-2 space-y-1">
                    {files.length === 0 ? (
                      <p className="px-3 py-4 text-[11px] text-muted-foreground text-center">
                        Upload files to give Duncan context about your project
                      </p>
                    ) : (
                      files.map(file => {
                        const extracting = isExtracting(file.id);
                        return (
                          <div key={file.id} className="group flex items-start gap-2 rounded-md p-2 hover:bg-secondary/60 transition-colors">
                            <FileText className="h-4 w-4 shrink-0 mt-0.5 text-muted-foreground" />
                            <div className="flex-1 min-w-0">
                              <p className="text-[11px] font-medium text-foreground truncate">{file.file_name}</p>
                              {extracting ? (
                                <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                                  <Loader2 className="h-3 w-3 animate-spin" /> Indexing...
                                </span>
                              ) : file.extracted_text ? (
                                <div className="flex items-center gap-2">
                                  <span className="text-[10px] text-emerald-500 dark:text-emerald-400 flex items-center gap-1">
                                    <Sparkles className="h-2.5 w-2.5" /> Indexed
                                  </span>
                                  <button
                                    onClick={() => extractText(file.id)}
                                    className="text-[10px] text-muted-foreground hover:text-primary"
                                    title="Re-index file"
                                  >
                                    <RefreshCw className="h-2.5 w-2.5" />
                                  </button>
                                </div>
                              ) : (
                                <button
                                  onClick={() => extractText(file.id)}
                                  className="text-[10px] text-primary hover:underline"
                                >
                                  Index file
                                </button>
                              )}
                            </div>
                            <button
                              onClick={() => { if (confirm("Delete this file?")) deleteFile(file.id); }}
                              className="opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded text-muted-foreground hover:text-destructive transition-all"
                              title="Delete file"
                            >
                              <Trash2 className="h-3 w-3" />
                            </button>
                          </div>
                        );
                      })
                    )}
                  </div>
                </ScrollArea>
              </div>
            </div>
          )}

          {/* Team Slide-over */}
          {showTeam && (
            <div className="fixed inset-0 z-40 flex justify-end">
              <div className="absolute inset-0 bg-black/30" onClick={() => setShowTeam(false)} />
              <div className="relative w-96 max-w-full bg-background border-l border-border flex flex-col shadow-xl animate-in slide-in-from-right duration-200">
                <div className="p-3 border-b border-border flex items-center justify-between">
                  <h3 className="text-xs font-semibold text-foreground">Project Team</h3>
                  <button onClick={() => setShowTeam(false)} className="flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors">
                    <X className="h-4 w-4" />
                  </button>
                </div>
                <ScrollArea className="flex-1">
                  <ProjectTeamTab
                    members={members}
                    availableProfiles={availableProfiles}
                    onAdd={addMember}
                    onRemove={removeMember}
                    canManage={project.user_id === user?.id || isAdmin}
                  />
                </ScrollArea>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Settings Dialog */}
      <Dialog open={showSettings} onOpenChange={setShowSettings}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Project Settings</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">Project Name</label>
              <Input value={editName} onChange={(e) => setEditName(e.target.value)} />
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">System Instructions</label>
              <Textarea
                value={editPrompt}
                onChange={(e) => setEditPrompt(e.target.value)}
                placeholder="Custom instructions for AI behavior in this project..."
                rows={6}
              />
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">
                Note Template <span className="text-muted-foreground font-normal">(optional)</span>
              </label>
              <Textarea
                value={editTemplate}
                onChange={(e) => setEditTemplate(e.target.value)}
                placeholder={"# Topic\n\n## Context\n- \n\n## Decisions\n- \n\n## Action items\n- [ ] \n"}
                rows={8}
                className="font-mono text-xs"
              />
              <p className="text-[11px] text-muted-foreground mt-1">
                Used as the starting content when you create a new note in this project. Leave blank to use the default.
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowSettings(false)}>Cancel</Button>
            <Button onClick={saveSettings} disabled={!editName.trim()}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showCollaborate} onOpenChange={setShowCollaborate}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Collaborate</DialogTitle>
            <DialogDescription>Add teammates to this project and share the chat workspace.</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="flex gap-2">
              <select
                value={selectedMemberId}
                onChange={(e) => setSelectedMemberId(e.target.value)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground"
              >
                <option value="">Select a teammate</option>
                {availableProfiles.map((profile) => (
                  <option key={profile.user_id} value={profile.user_id}>
                    {profile.display_name || profile.role_title || profile.user_id}
                  </option>
                ))}
              </select>
              <Button onClick={handleAddMember} disabled={!selectedMemberId}>Add</Button>
            </div>

            <div className="rounded-md border border-border">
              {membersLoading ? (
                <div className="flex items-center justify-center py-6 text-sm text-muted-foreground">
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading members...
                </div>
              ) : members.length === 1 ? (
                <div className="px-4 py-6 text-sm text-muted-foreground">
                  Only you have access to this project right now.
                </div>
              ) : null}

              <div className="divide-y divide-border">
                {members.map((member) => (
                  <div key={member.user_id} className="flex items-center gap-3 px-4 py-3">
                    <Avatar className="h-9 w-9">
                      <AvatarImage src={member.avatar_url || undefined} alt={member.display_name || "Project member"} />
                      <AvatarFallback>{initialsFor(member.display_name)}</AvatarFallback>
                    </Avatar>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <p className="truncate text-sm font-medium text-foreground">{member.display_name || "Unnamed user"}</p>
                        {member.isOwner && (
                          <span className="rounded-sm bg-secondary px-2 py-0.5 text-[10px] font-medium text-secondary-foreground">Owner</span>
                        )}
                      </div>
                      {member.role_title && <p className="truncate text-xs text-muted-foreground">{member.role_title}</p>}
                    </div>
                    {!member.isOwner && (
                      <Button variant="ghost" size="sm" onClick={() => removeMember(member.user_id)}>
                        Remove
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCollaborate(false)}>Close</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>



    </div>
  );
}
