import { useState, useRef, useEffect, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  ArrowLeft, Plus, MessageSquare, Send, Loader2, Settings2, Users,
  Upload, FileText, Sparkles, Trash2, RefreshCw, PanelRightOpen, X, Menu, ListChecks,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import Sidebar, { MobileMenuButton } from "@/components/Sidebar";
import { supabase } from "@/integrations/supabase/client";
import { useProjects, useProjectChats, useProjectChat, useProjectFiles, useProjectMembers } from "@/hooks/useProjects";
import { useUserProfiles } from "@/hooks/useWorkstreams";
import { useProfile } from "@/hooks/useProfile";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import duncanAvatar from "@/assets/duncan-avatar.jpeg";
import { generateChatTitle, isAutoGeneratedTitle } from "@/lib/generateChatTitle";
import { PlanningChecklist } from "@/components/projects/PlanningChecklist";
import { ProjectTasksDrawer } from "@/components/projects/ProjectTasksDrawer";
import { toast } from "sonner";

const CHECKLIST_RE = /^\s*[-*]\s*\[\s*[ xX]?\s*\]\s+/;
const HEADING_RE = /^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$/;

function hasChecklist(text: string): boolean {
  if (!text) return false;
  return text.split("\n").some((l) => CHECKLIST_RE.test(l));
}

async function captureChecklistToPlan(text: string, chatId: string, projectId: string) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    toast.error("Not signed in");
    return;
  }
  const lines = text.split("\n");
  let currentGroup: string | null = null;
  const items: Array<{ title: string; group: string | null }> = [];
  for (const raw of lines) {
    const heading = raw.match(HEADING_RE);
    if (heading) {
      currentGroup = heading[2].trim();
      continue;
    }
    if (CHECKLIST_RE.test(raw)) {
      const title = raw.replace(CHECKLIST_RE, "").trim();
      if (title) items.push({ title, group: currentGroup });
    }
  }
  if (items.length === 0) {
    toast("No checklist items detected");
    return;
  }
  // Get current max position
  const { data: existing } = await supabase
    .from("project_chat_plan_items" as any)
    .select("position")
    .eq("chat_id", chatId)
    .order("position", { ascending: false })
    .limit(1);
  const startPos = ((existing as any[])?.[0]?.position ?? 0) + 1;
  const rows = items.map((it, i) => ({
    chat_id: chatId,
    project_id: projectId,
    created_by: user.id,
    title: it.title,
    group_title: it.group,
    status: "accepted" as const,
    position: startPos + i,
  }));
  const { error } = await supabase.from("project_chat_plan_items" as any).insert(rows);
  if (error) {
    toast.error(`Couldn't add: ${error.message}`);
    return;
  }
  toast.success(`Added ${items.length} item${items.length === 1 ? "" : "s"} to Planning checklist`);
}

export default function ProjectWorkspace() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { projects, loading: projectsLoading, updateProject } = useProjects();
  const project = projects.find(p => p.id === projectId) || null;
  const { chats, loading: chatsLoading, createChat, updateChatTitle, deleteChat } = useProjectChats(projectId || null);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const { messages, loading: msgsLoading, sending, sendMessage } = useProjectChat(activeChatId);
  const { files, uploadFile, extractText, deleteFile, isUploading, isExtracting } = useProjectFiles(projectId || null);
  const { members, loading: membersLoading, addMember, removeMember } = useProjectMembers(projectId || null);
  const { data: userProfiles = [] } = useUserProfiles({ approvedOnly: false });
  const { profile: currentProfile } = useProfile();
  const myDisplayName = currentProfile?.display_name || "You";
  const myAvatarUrl = currentProfile?.avatar_url || null;

  const [mobileOpen, setMobileOpen] = useState(false);
  const [chatListOpen, setChatListOpen] = useState(false);
  const [input, setInput] = useState("");
  const [showSettings, setShowSettings] = useState(false);
  const [showFiles, setShowFiles] = useState(false);
  const [showCollaborate, setShowCollaborate] = useState(false);
  const [showTasks, setShowTasks] = useState(false);
  const [openTaskCount, setOpenTaskCount] = useState(0);
  const [editName, setEditName] = useState("");
  const [editPrompt, setEditPrompt] = useState("");
  const [selectedMemberId, setSelectedMemberId] = useState("");
  const [manualDeselect, setManualDeselect] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const cleanedUpRef = useRef(false);
  const titledChatsRef = useRef<Set<string>>(new Set());

  // Clean up empty chats on load (chats titled "New Chat" with no messages)
  useEffect(() => {
    if (chatsLoading || cleanedUpRef.current || chats.length === 0) return;
    cleanedUpRef.current = true;
    const cleanupEmpty = async () => {
      for (const chat of chats) {
        if (chat.title === "New Chat") {
          const { data } = await supabase
            .from("chat_messages")
            .select("id")
            .eq("chat_id", chat.id)
            .limit(1);
          if (!data || data.length === 0) {
            await deleteChat(chat.id);
          }
        }
      }
    };
    cleanupEmpty();
  }, [chatsLoading, chats, deleteChat]);

  // Reset cleanup flag when project changes
  useEffect(() => {
    cleanedUpRef.current = false;
    setManualDeselect(false);
    setActiveChatId(null);
  }, [projectId]);

  // Auto-select first chat (unless user manually deselected)
  useEffect(() => {
    if (chats.length > 0 && !activeChatId && !manualDeselect) {
      setActiveChatId(chats[0].id);
    }
  }, [chats, activeChatId, manualDeselect]);

  // Project-wide open task count (badge on Tasks button) + realtime
  useEffect(() => {
    if (!projectId) return;
    let cancelled = false;
    const fetchCount = async () => {
      const { count } = await supabase
        .from("project_chat_plan_items" as any)
        .select("id", { count: "exact", head: true })
        .eq("project_id", projectId)
        .in("status", ["accepted", "suggested"]);
      if (!cancelled) setOpenTaskCount(count || 0);
    };
    fetchCount();
    const channel = supabase
      .channel(`project_task_count:${projectId}`)
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "project_chat_plan_items", filter: `project_id=eq.${projectId}` },
        () => fetchCount(),
      )
      .subscribe();
    return () => {
      cancelled = true;
      supabase.removeChannel(channel);
    };
  }, [projectId]);

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Auto-resize textarea
  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 160) + "px";
  }, [input]);

  const handleSend = useCallback(async () => {
    if (!input.trim() || sending) return;
    const msg = input.trim();
    setInput("");

    let chatId = activeChatId;

    // If no active chat, create one on first message
    if (!chatId) {
      const title = msg.length > 50 ? msg.slice(0, 47) + "..." : msg;
      const chat = await createChat(title);
      if (!chat) return;
      chatId = chat.id;
      setActiveChatId(chat.id);
      setManualDeselect(false);
    }

    // Pass chatId directly to handle the case where activeChatId just changed
    const reply = await sendMessage(msg, chatId);

    // Intelligent title generation — once per chat, async, non-blocking
    if (reply && chatId && !titledChatsRef.current.has(chatId)) {
      const currentChat = chats.find((c) => c.id === chatId);
      if (currentChat && isAutoGeneratedTitle(currentChat.title)) {
        const targetChatId = chatId;
        titledChatsRef.current.add(targetChatId);
        (async () => {
          const titleMessages = [
            { role: "user" as const, content: msg },
            { role: "assistant" as const, content: reply },
          ];
          const newTitle = await generateChatTitle(titleMessages);
          if (newTitle) {
            await updateChatTitle(targetChatId, newTitle);
          } else {
            titledChatsRef.current.delete(targetChatId);
          }
        })();
      }
    }
  }, [input, sending, sendMessage, activeChatId, createChat, chats, updateChatTitle]);

  const handleNewChat = () => {
    // Just deselect current chat - a new chat will be created on first message
    setActiveChatId(null);
    setManualDeselect(true);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const fileList = e.target.files;
    if (!fileList) return;
    for (const file of Array.from(fileList)) {
      await uploadFile(file);
    }
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const openSettings = () => {
    setEditName(project?.name || "");
    setEditPrompt(project?.system_prompt || "");
    setShowSettings(true);
  };

  const saveSettings = async () => {
    if (!projectId) return;
    await updateProject(projectId, { name: editName.trim(), system_prompt: editPrompt.trim() || null });
    setShowSettings(false);
  };

  const memberIds = new Set(members.map((member) => member.user_id));
  const availableProfiles = userProfiles.filter((profile) => profile.user_id !== project?.user_id && !memberIds.has(profile.user_id));

  const handleAddMember = async () => {
    if (!selectedMemberId) return;
    const ok = await addMember(selectedMemberId);
    if (ok) setSelectedMemberId("");
  };

  const initialsFor = (name: string | null) =>
    (name || "?")
      .split(" ")
      .filter(Boolean)
      .slice(0, 2)
      .map((part) => part[0]?.toUpperCase())
      .join("") || "?";

  const senderNameFor = (msg: typeof messages[number]) => {
    if (msg.role === "assistant") return "Duncan";
    return msg.sender_name || myDisplayName;
  };

  if (!projectId) return null;

  // Show loading while projects are being fetched
  if (projectsLoading) {
    return (
      <div className="flex h-screen overflow-hidden bg-background">
        <Sidebar mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen(false)} />
        <main className="flex-1 lg:ml-64 flex items-center justify-center">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </main>
      </div>
    );
  }

  // Show not-found if project doesn't exist after loading
  if (!project) {
    return (
      <div className="flex h-screen overflow-hidden bg-background">
        <Sidebar mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen(false)} />
        <main className="flex-1 lg:ml-64 flex flex-col items-center justify-center gap-3">
          <p className="text-sm text-muted-foreground">Project not found</p>
          <Button variant="outline" size="sm" onClick={() => navigate("/projects")}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Projects
          </Button>
        </main>
      </div>
    );
  }

  // Count extracted files for status indicator
  const extractedCount = files.filter(f => f.extracted_text).length;

  return (
    <div className="flex h-screen overflow-hidden bg-background">
      <Sidebar mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen(false)} />
      <main className="flex-1 lg:ml-64 flex flex-col min-h-0">
        {/* Header */}
        <header className="flex items-center gap-1.5 sm:gap-3 border-b border-border px-2 sm:px-4 py-3 shrink-0">
          <MobileMenuButton onClick={() => setMobileOpen(true)} />
          <button onClick={() => navigate("/projects")} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors">
            <ArrowLeft className="h-4 w-4" />
          </button>
          <button
            onClick={() => setChatListOpen(true)}
            className="md:hidden flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors"
            aria-label="Open chat list"
          >
            <Menu className="h-4 w-4" />
          </button>
          <div className="flex-1 min-w-0">
            <h1 className="text-sm font-semibold text-foreground truncate">{project.name}</h1>
            <p className="text-[10px] text-muted-foreground truncate hidden sm:block">
              {extractedCount > 0
                ? `${extractedCount} file${extractedCount !== 1 ? "s" : ""} indexed • Auto-retrieval active`
                : project.system_prompt ? "Custom instructions active" : "Default instructions"}
            </p>
          </div>
          <Button variant="ghost" size="sm" onClick={() => setShowFiles(true)} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Files">
            <FileText className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Files{files.length > 0 && ` (${files.length})`}</span>
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setShowTasks(true)} className="gap-1.5 text-xs px-2 sm:px-3 relative" aria-label="Tasks">
            <ListChecks className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Tasks{openTaskCount > 0 && ` (${openTaskCount})`}</span>
            {openTaskCount > 0 && (
              <span className="sm:hidden absolute -top-0.5 -right-0.5 inline-flex h-4 min-w-[16px] items-center justify-center rounded-full bg-primary text-primary-foreground text-[9px] font-medium px-1">
                {openTaskCount}
              </span>
            )}
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setShowCollaborate(true)} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Collaborate">
            <Users className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Collaborate</span>
          </Button>
          <Button variant="ghost" size="sm" onClick={openSettings} className="gap-1.5 text-xs px-2 sm:px-3" aria-label="Settings">
            <Settings2 className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Settings</span>
          </Button>
        </header>

        {/* Workspace */}
        <div className="flex-1 flex min-h-0">
          {/* LEFT: Chat list (desktop) */}
          <div className="w-56 shrink-0 border-r border-border flex-col bg-sidebar/50 hidden md:flex">
            <div className="p-3 border-b border-border">
              <Button variant="outline" size="sm" onClick={handleNewChat} className="w-full gap-2 text-xs">
                <Plus className="h-3.5 w-3.5" />
                New Chat
              </Button>
            </div>
            <ScrollArea className="flex-1">
              <div className="p-2 space-y-0.5">
                {chats.map(chat => (
                  <div
                    key={chat.id}
                    className={`group grid grid-cols-[minmax(0,1fr)_2rem] items-center w-full min-w-0 rounded-md text-xs font-medium transition-colors ${
                      activeChatId === chat.id
                        ? "bg-primary/10 text-primary"
                        : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"
                    }`}
                  >
                    <button
                      type="button"
                      onClick={() => setActiveChatId(chat.id)}
                      className="flex items-center gap-2 min-w-0 px-3 py-2 text-left"
                    >
                      <MessageSquare className="h-3.5 w-3.5 shrink-0" />
                      <span className="min-w-0 truncate">{chat.title}</span>
                    </button>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        if (confirm(`Delete chat "${chat.title}"? This cannot be undone.`)) {
                          deleteChat(chat.id);
                          if (activeChatId === chat.id) setActiveChatId(null);
                        }
                      }}
                      className="h-8 w-8 flex items-center justify-center rounded text-destructive hover:bg-destructive/10 transition-colors"
                      title="Delete chat"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </div>
                ))}
                {chats.length === 0 && !chatsLoading && (
                  <p className="px-3 py-4 text-[11px] text-muted-foreground text-center">
                    No chats yet
                  </p>
                )}
              </div>
            </ScrollArea>
          </div>

          {/* LEFT: Chat list (mobile drawer) */}
          {chatListOpen && (
            <div className="md:hidden fixed inset-0 z-50 flex">
              <div className="absolute inset-0 bg-black/40" onClick={() => setChatListOpen(false)} />
              <div className="relative w-64 max-w-[80%] bg-background border-r border-border flex flex-col shadow-xl animate-in slide-in-from-left duration-200">
                <div className="flex items-center justify-between p-3 border-b border-border">
                  <h3 className="text-sm font-semibold">Chats</h3>
                  <button onClick={() => setChatListOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60">
                    <X className="h-4 w-4" />
                  </button>
                </div>
                <div className="p-3 border-b border-border">
                  <Button variant="outline" size="sm" onClick={() => { handleNewChat(); setChatListOpen(false); }} className="w-full gap-2 text-xs">
                    <Plus className="h-3.5 w-3.5" />
                    New Chat
                  </Button>
                </div>
                <ScrollArea className="flex-1">
                  <div className="p-2 space-y-0.5">
                    {chats.map(chat => (
                      <div
                        key={chat.id}
                        className={`group flex items-center gap-1 w-full min-w-0 rounded-md pr-1 text-xs font-medium transition-colors ${
                          activeChatId === chat.id
                            ? "bg-primary/10 text-primary"
                            : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"
                        }`}
                      >
                        <button
                          onClick={() => { setActiveChatId(chat.id); setChatListOpen(false); }}
                          className="flex items-center gap-2 flex-1 min-w-0 px-3 py-2 text-left"
                        >
                          <MessageSquare className="h-3.5 w-3.5 shrink-0" />
                          <span className="truncate">{chat.title}</span>
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            if (confirm(`Delete chat "${chat.title}"? This cannot be undone.`)) {
                              deleteChat(chat.id);
                              if (activeChatId === chat.id) setActiveChatId(null);
                            }
                          }}
                          className="shrink-0 h-7 w-7 flex items-center justify-center rounded text-muted-foreground hover:text-destructive transition-colors"
                          title="Delete chat"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    ))}
                    {chats.length === 0 && !chatsLoading && (
                      <p className="px-3 py-4 text-[11px] text-muted-foreground text-center">
                        No chats yet
                      </p>
                    )}
                  </div>
                </ScrollArea>
              </div>
            </div>
          )}

          {/* CENTER: Chat */}
          <div className="flex-1 flex flex-col min-w-0">
            {!activeChatId ? (
              <div className="flex-1 flex flex-col">
                <div className="flex-1 flex flex-col items-center justify-center text-center p-6">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 mb-4">
                    <MessageSquare className="h-7 w-7 text-primary" />
                  </div>
                  <h2 className="text-base font-semibold text-foreground mb-1">Start a conversation</h2>
                  <p className="text-sm text-muted-foreground">Type a message below to begin working with Duncan in this project.</p>
                </div>
                {/* Input for new chat */}
                <div className="border-t border-border px-4 py-3">
                  <div className="max-w-3xl mx-auto flex items-end gap-3 rounded-xl border border-border bg-card px-4 py-3 focus-within:border-primary/40 transition-all">
                    <textarea
                      ref={textareaRef}
                      placeholder="Message Duncan..."
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); } }}
                      disabled={sending}
                      rows={1}
                      className="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none disabled:opacity-50 resize-none overflow-y-auto"
                      style={{ maxHeight: 160 }}
                    />
                    <button
                      onClick={handleSend}
                      disabled={!input.trim() || sending}
                      className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground transition-all hover:bg-primary/90 disabled:opacity-30"
                    >
                      {sending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Send className="h-3.5 w-3.5" />}
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              <>
                {projectId && activeChatId && (
                  <PlanningChecklist
                    chatId={activeChatId}
                    projectId={projectId}
                    chatTitle={chats.find((c) => c.id === activeChatId)?.title}
                    projectName={project?.name}
                    members={members}
                    currentUserId={currentProfile?.user_id || null}
                  />
                )}
                {/* Messages */}
                <ScrollArea className="flex-1 p-4">
                  <div className="max-w-3xl mx-auto space-y-4">
                    {msgsLoading && (
                      <div className="flex justify-center py-8">
                        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                      </div>
                    )}
                    {messages.map(msg => {
                      const isUser = msg.role === "user";
                      const userMember = isUser ? members.find((m) => m.user_id === msg.user_id) : null;
                      const userName = isUser ? (msg.sender_name || userMember?.display_name || myDisplayName) : "Duncan";
                      const userAvatar = isUser ? (userMember?.avatar_url || myAvatarUrl) : null;
                      return (
                        <div key={msg.id} className={`flex gap-2 sm:gap-3 ${isUser ? "justify-end" : ""}`}>
                          {!isUser && (
                            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg overflow-hidden border border-primary/20">
                              <img src={duncanAvatar} alt="Duncan" className="h-full w-full object-cover object-[50%_30%] scale-150" />
                            </div>
                          )}
                          <div className={`max-w-[85%] sm:max-w-[80%] space-y-1 ${isUser ? "items-end" : "items-start"}`}>
                            <p className={`text-[10px] font-medium uppercase tracking-wider text-muted-foreground ${isUser ? "text-right" : "text-left"}`}>
                              {senderNameFor(msg)}
                            </p>
                            <div className={`rounded-xl px-4 py-3 text-sm ${
                              isUser
                                ? "bg-primary text-primary-foreground"
                                : "bg-card border border-border text-foreground"
                            }`}>
                              {!isUser ? (
                                <div className="prose prose-sm dark:prose-invert max-w-none">
                                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content}</ReactMarkdown>
                                </div>
                              ) : (
                                <p className="whitespace-pre-wrap break-words">{msg.content}</p>
                              )}
                            </div>
                            {!isUser && activeChatId && projectId && hasChecklist(msg.content) && (
                              <button
                                onClick={() => captureChecklistToPlan(msg.content, activeChatId, projectId)}
                                className="text-[10px] inline-flex items-center gap-1 text-primary hover:underline mt-1"
                              >
                                <Plus className="h-3 w-3" /> Add checklist to Planning
                              </button>
                            )}
                          </div>
                          {isUser && (
                            <Avatar className="h-7 w-7 shrink-0 border border-primary/20">
                              {userAvatar ? <AvatarImage src={userAvatar} alt={userName} /> : null}
                              <AvatarFallback className="text-[10px] font-semibold bg-primary/10 text-primary">
                                {initialsFor(userName)}
                              </AvatarFallback>
                            </Avatar>
                          )}
                        </div>
                      );
                    })}
                    {sending && (
                      <div className="flex gap-3">
                        <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg overflow-hidden border border-primary/20">
                          <img src={duncanAvatar} alt="Duncan" className="h-full w-full object-cover object-[50%_30%] scale-150" />
                        </div>
                        <div className="rounded-xl bg-card border border-border px-4 py-3">
                          <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                        </div>
                      </div>
                    )}
                    <div ref={messagesEndRef} />
                  </div>
                </ScrollArea>

                {/* Input */}
                <div className="border-t border-border px-4 py-3">
                  <div className="max-w-3xl mx-auto flex items-end gap-3 rounded-xl border border-border bg-card px-4 py-3 focus-within:border-primary/40 transition-all">
                    <textarea
                      ref={textareaRef}
                      placeholder="Message Duncan..."
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); } }}
                      disabled={sending}
                      rows={1}
                      className="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none disabled:opacity-50 resize-none overflow-y-auto"
                      style={{ maxHeight: 160 }}
                    />
                    <button
                      onClick={handleSend}
                      disabled={!input.trim() || sending}
                      className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground transition-all hover:bg-primary/90 disabled:opacity-30"
                    >
                      <Send className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>

          {/* Files Slide-over */}
          {showFiles && (
            <div className="fixed inset-0 z-40 flex justify-end">
              <div className="absolute inset-0 bg-black/30" onClick={() => setShowFiles(false)} />
              <div className="relative w-72 max-w-full bg-background border-l border-border flex flex-col shadow-xl animate-in slide-in-from-right duration-200">
                <div className="p-3 border-b border-border flex items-center justify-between">
                  <h3 className="text-xs font-semibold text-foreground">Project Files</h3>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isUploading}
                      className="h-7 px-2 gap-1 text-[10px]"
                    >
                      {isUploading ? (
                        <Loader2 className="h-3 w-3 animate-spin" />
                      ) : (
                        <Upload className="h-3 w-3" />
                      )}
                      {isUploading ? "Uploading..." : "Upload"}
                    </Button>
                    <button onClick={() => setShowFiles(false)} className="flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary/60 transition-colors">
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                </div>
                {extractedCount > 0 && (
                  <div className="flex items-center gap-1.5 text-[10px] text-primary px-3 py-1.5 border-b border-border">
                    <Sparkles className="h-3 w-3" />
                    <span>Auto-retrieval active</span>
                  </div>
                )}
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  className="hidden"
                  accept=".pdf,.docx,.txt,.md,.csv,.json,.xml,.yaml,.yml"
                  onChange={handleFileUpload}
                  disabled={isUploading}
                />
                <ScrollArea className="flex-1">
                  <div className="p-2 space-y-1">
                    {files.length === 0 ? (
                      <p className="px-3 py-4 text-[11px] text-muted-foreground text-center">
                        Upload files to give Duncan context about your project
                      </p>
                    ) : (
                      files.map(file => {
                        const extracting = isExtracting(file.id);
                        return (
                          <div key={file.id} className="group flex items-start gap-2 rounded-md p-2 hover:bg-secondary/60 transition-colors">
                            <FileText className="h-4 w-4 shrink-0 mt-0.5 text-muted-foreground" />
                            <div className="flex-1 min-w-0">
                              <p className="text-[11px] font-medium text-foreground truncate">{file.file_name}</p>
                              {extracting ? (
                                <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                                  <Loader2 className="h-3 w-3 animate-spin" /> Indexing...
                                </span>
                              ) : file.extracted_text ? (
                                <div className="flex items-center gap-2">
                                  <span className="text-[10px] text-emerald-500 dark:text-emerald-400 flex items-center gap-1">
                                    <Sparkles className="h-2.5 w-2.5" /> Indexed
                                  </span>
                                  <button
                                    onClick={() => extractText(file.id)}
                                    className="text-[10px] text-muted-foreground hover:text-primary"
                                    title="Re-index file"
                                  >
                                    <RefreshCw className="h-2.5 w-2.5" />
                                  </button>
                                </div>
                              ) : (
                                <button
                                  onClick={() => extractText(file.id)}
                                  className="text-[10px] text-primary hover:underline"
                                >
                                  Index file
                                </button>
                              )}
                            </div>
                            <button
                              onClick={() => { if (confirm("Delete this file?")) deleteFile(file.id); }}
                              className="opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded text-muted-foreground hover:text-destructive transition-all"
                              title="Delete file"
                            >
                              <Trash2 className="h-3 w-3" />
                            </button>
                          </div>
                        );
                      })
                    )}
                  </div>
                </ScrollArea>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Settings Dialog */}
      <Dialog open={showSettings} onOpenChange={setShowSettings}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Project Settings</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">Project Name</label>
              <Input value={editName} onChange={(e) => setEditName(e.target.value)} />
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">System Instructions</label>
              <Textarea
                value={editPrompt}
                onChange={(e) => setEditPrompt(e.target.value)}
                placeholder="Custom instructions for AI behavior in this project..."
                rows={6}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowSettings(false)}>Cancel</Button>
            <Button onClick={saveSettings} disabled={!editName.trim()}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showCollaborate} onOpenChange={setShowCollaborate}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Collaborate</DialogTitle>
            <DialogDescription>Add teammates to this project and share the chat workspace.</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="flex gap-2">
              <select
                value={selectedMemberId}
                onChange={(e) => setSelectedMemberId(e.target.value)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground"
              >
                <option value="">Select a teammate</option>
                {availableProfiles.map((profile) => (
                  <option key={profile.user_id} value={profile.user_id}>
                    {profile.display_name || profile.role_title || profile.user_id}
                  </option>
                ))}
              </select>
              <Button onClick={handleAddMember} disabled={!selectedMemberId}>Add</Button>
            </div>

            <div className="rounded-md border border-border">
              {membersLoading ? (
                <div className="flex items-center justify-center py-6 text-sm text-muted-foreground">
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading members...
                </div>
              ) : members.length === 1 ? (
                <div className="px-4 py-6 text-sm text-muted-foreground">
                  Only you have access to this project right now.
                </div>
              ) : null}

              <div className="divide-y divide-border">
                {members.map((member) => (
                  <div key={member.user_id} className="flex items-center gap-3 px-4 py-3">
                    <Avatar className="h-9 w-9">
                      <AvatarImage src={member.avatar_url || undefined} alt={member.display_name || "Project member"} />
                      <AvatarFallback>{initialsFor(member.display_name)}</AvatarFallback>
                    </Avatar>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <p className="truncate text-sm font-medium text-foreground">{member.display_name || "Unnamed user"}</p>
                        {member.isOwner && (
                          <span className="rounded-sm bg-secondary px-2 py-0.5 text-[10px] font-medium text-secondary-foreground">Owner</span>
                        )}
                      </div>
                      {member.role_title && <p className="truncate text-xs text-muted-foreground">{member.role_title}</p>}
                    </div>
                    {!member.isOwner && (
                      <Button variant="ghost" size="sm" onClick={() => removeMember(member.user_id)}>
                        Remove
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCollaborate(false)}>Close</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
